---
title: "LA City payroll data"
author: "Nandini Hegde"
date: "October 20, 2018"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos="https://cran.rstudio.com" )
```

source of dataset: https://controllerdata.lacity.org/Payroll/City-Employee-Payroll/pazn-qyym
Objective: to forecase the payroll expenses of all employess for Q1 and Q2 of 2018

## Install libraries and load dataset

```{r}
library('ggplot2')
library('forecast')
library('tseries')
library(tidyr)
library(zoo)
library(forecast)
library(Metrics)
library(dplyr)

payroll<- read.csv("Payroll Data for Datathon.csv")

```


## Examine the data

```{r}
str(payroll)

#remove columns which are not required for the model
payroll$Row.ID<-NULL
payroll$Job.Class.Link<-NULL
payroll$MOU<-NULL
payroll$MOU.Title<-NULL

summary(payroll)



```
## Data cleaning and Missing value treatment

```{r}
sapply(payroll, function(x) sum(is.na(x)))

#remove records with no record no
payroll<- payroll[!is.na(payroll$Record.Number),]

#replace missing payroll dept by fake dept NC
payroll[is.na(payroll$Payroll.Department),'Payroll.Department'] <- 'NC'

payroll[is.na(payroll$Hourly.or.Event.Rate),'Hourly.or.Event.Rate']<- payroll[is.na(payroll$Hourly.or.Event.Rate),'Projected.Annual.Salary']/2088

payroll[is.na(payroll$Payments.Over.Base.Pay),'Payments.Over.Base.Pay'] <- 0


payroll[is.na(payroll$X..Over.Base.Pay),'X..Over.Base.Pay']<-payroll[is.na(payroll$X..Over.Base.Pay),'Payments.Over.Base.Pay']/payroll[is.na(payroll$X..Over.Base.Pay),'Base.Pay']
payroll[is.na(payroll$Lump.Sum.Pay),'Lump.Sum.Pay'] <- 0
payroll[is.na(payroll$Overtime.Pay),'Overtime.Pay'] <- 0

# correct columns type
payroll$Payroll.Department<- as.factor(payroll$Payroll.Department)
payroll$FMS.Department<-as.factor(payroll$FMS.Department)
payroll$Job.Class<-as.factor(payroll$Job.Class)

```

# univariate time series model

## Data pre-processing for univariate time series model

```{r}


payroll_ts<-gather(payroll, key = time_var, value = Payments,Q1.Payments, Q2.Payments, Q3.Payments, Q4.Payments)
#subset required columns
payroll_ts<-payroll_ts[,c("Record.Number","Year","time_var","Payments")]

# converting quarter year to dates
payroll_ts$qtr_year <- paste(substr(payroll_ts$time_var,1,2),"/",substr(payroll_ts$Year,3,4), sep = "")

payroll_ts$date<-as.Date(as.yearqtr(payroll_ts$qtr_year, format = "Q%q/%y"))

#dropping redundant colums
payroll_ts[,c("Year","time_var","qtr_year")]<-NULL

payroll_ts$Payments<-ts(payroll_ts$Payments)

# Sort by vector `CustomerName` then `variable`
payroll_ts<-payroll_ts[with(payroll_ts, order(Record.Number, date)),]
payroll_ts<-payroll_ts[,c(1,3,2)] # reordering the columns


```
## model fitting

```{r}

# splitting data into train and valid sets
train = payroll_ts[payroll_ts$date<="2017-12-31",]
valid = payroll_ts[payroll_ts$date>"2017-12-31",]
valid=valid[valid$date<="2018-01-01",]




#Fit a model for every employee
(model_fits <- group_by(train, Record.Number) %>% do(fit=auto.arima(.$Payments)))
#The result is a data frame containing the model fits for each CustomerName:

#You can get a list with each model fit like so:
(fitted<-model_fits$fit)
sapply(fitted[1:5], function(x) plot(forecast(x, 1)))





```
## forecast for the next quarter

```{r}
# forecasting
forecast=sapply(fitted, function(x) forecast(x, 1)$mean)
model_fits$forecast<-forecast



```
## calculate RMSE

```{r}
valid<-merge(valid,model_fits, by="Record.Number", all.x= TRUE)

valid_clean<-na.omit(valid)

# evaluation
rmse(valid_clean$Payments, valid_clean$forecast)

```
